# Generated by Django 4.2.8 on 2024-05-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="product",
            name="available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["name"], name="item_catego_name_6c02f0_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["id"], name="item_produc_id_22076d_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="item_produc_name_c3ee18_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created_at"], name="item_produc_created_7271bc_idx"
            ),
        ),
    ]
