# Generated by Django 4.2.8 on 2024-05-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0003_category_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
