# Generated by Django 4.2.8 on 2024-05-20 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0004_product_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
    ]
