# Generated by Django 4.2.8 on 2024-06-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0005_remove_category_slug_remove_product_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="available",
            field=models.BooleanField(),
        ),
    ]
