# Generated by Django 4.2.8 on 2024-06-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0007_category_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="expiration_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
