# Generated by Django 4.2.8 on 2024-06-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0008_product_expiration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="product_images/"),
        ),
    ]
