# Generated by Django 4.2.8 on 2024-06-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0009_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
